server:
  port: 10010
spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: localhost:8848  #nacos地址
      discovery:
        group: LLPY
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice #路由的目标地址
          predicates:  #路由断言，判断请求是否符合规则
            - Path=/user/**  # 路由断言，判断路径是否是以/user开头

        - id: photo-service
          uri: lb://photoservice #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/photo/**  # 路由断言

        - id: text-service
          uri: lb://textservice #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/text/**  # 路由断言

      default-filters:
        - StripPrefix=1  #忽略一级请求前缀

  datasource:
    url: jdbc:mysql://localhost:3306/llpyblog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver



  redis:
    host: localhost
    database: 0
    port: 6379


