server:
  port: 8083

spring:

  profiles:
    active: dev

  application:
    name: userservice  #服务名称

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos地址
        group: LLPY


  #redis配置
  redis:
    host: localhost
    database: 0
    port: 6379

  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  mail:
    host: smtp.qq.com #SMTP服务器
    port: 587
    username: 309829291@qq.com #发件人
    password: iibgaqdurqcvbjia #授权码
    properties:
      from: 309829291@qq.com #发件人信息
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory



#配置阿里云属性
aliyun:
  oss:
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tSi8iMHaqgxAw5bdBgS
    accessKeySecret: HebfvTRyALJMuH6grBSVm0cwDtZsmc
    bucketName: llpy-blog
    directory: userImg







