server:
  port: 8083

spring:
  application:
    name: userservice

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/llpyblog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  cloud:
    nacos:
      server-addr: localhost:8848  #nacos??
      discovery:
        group: LLPY
  redis:
    host: localhost
    database: 0
    port: 6379
  druid:
    test-on-borrow: true
    test-while-idle: true




