server:
  port: 8082

spring:
  application:
    name: textservice
  profiles:
    include: secret

  #日志信息
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/llpyblog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456

  cloud:
    nacos:
      server-addr: localhost:8848  #nacos??
      discovery:
        group: LLPY
  redis:
    host: localhost
    database: 0
    port: 6379

  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

